baseURL = "https://greenbayseo.com"
languageCode = "en-us"
title = "Green Bay Ranking Co."
enableRobotsTXT = true
paginate = "12"
summaryLength = 20

#################### default parameters ################################

[params]
  minifyBundles = true
  imgixDomain = ""

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[markup.goldmark.renderer]
  unsafe= true

[module]
replacements = "components.local -> ../component-library"

[[module.imports]]
path = 'components.local'

[[module.imports]]
path = 'github.com/cloudcannon/bookshop/hugo/v3'

[taxonomies]
  category = 'categories'

[related]
  includeNewer = true
  threshold = 80
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 100