# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Two Columns Block
  description: Two Columns Block
  icon: view_column_2
  tags: ["Page Components"]

# Defines the structure of this component, as well as the default values
blueprint:
  preheading: ''
  heading: ''
  body: >-
    
  left_column:
    preheading: ''
    heading: ''
    body: >-

    button:
      enabled: true
      button_url: '' 
      button_text: ''
      button_color: ''
      open_in_new_tab: false
    text_align: ''
  right_column:
    preheading: ''
    heading: ''
    body: >-
      
    button:
      enabled: true
      button_url: '' 
      button_text: ''
      button_color: ''
      open_in_new_tab: false
    text_align: ''
  background_color: gray
  overlay_color: black
  background_image:
    image_url: ''
    image_alt: ''
  css_class: ''

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
